#!/bin/bash

java -jar VeracodeJavaAPI.jar -vid "$VERACODE_API_ID" -vkey "$VERACODE_API_KEY" -action detailedreport -buildid "$VERACODE_BUILD_ID" -outputfilepath veracoderesults.txt

echo 'Veracode Scan Output'
echo '-----------------------------------------'
echo `cat veracoderesults.txt`
echo '-----------------------------------------'
echo 'Veracode Scan result'
echo '-----------------------------------------'

EXCEPTIONS="
CVE-2022-22965
CVE-2020-9493
CVE-2019-17571
CVE-2022-23305
CVE-2022-47937
CVE-2015-4852
CVE-2025-24813
CVE-2024-50379
CVE-2024-52316
CVE-2016-1000031
CVE-2022-1471
CVE-2016-1000027
CVE-2017-1000487
CVE-2024-23672
CVE-2020-13935
CVE-2021-40690
CVE-2023-6378
CVE-2015-0254
CVE-2022-23307
CVE-2021-4104
CVE-2023-26464
CVE-2022-23302
CVE-2024-8698
SRCCLR-SID-49226
CVE-2017-2646
CVE-2024-38819
CVE-2024-38816
CVE-2023-20883
CVE-2023-46589
CVE-2024-24549
CVE-2023-28709
CVE-2024-34750
CVE-2023-44487
CVE-2021-25122
CVE-2021-25329
CVE-2020-13934
CVE-2022-23181
CVE-2020-17527
CVE-2024-47554
CVE-2023-24998
CVE-2021-42340
CVE-2022-25857
CVE-2021-46877
CVE-2020-36518
CVE-2022-42003
CVE-2022-42004
CVE-2024-22243
CVE-2024-22259
CVE-2024-22262
CVE-2021-22118
CVE-2012-5783
CVE-2019-2692
CVE-2022-21363
CVE-2021-22096
CVE-2021-42550
CVE-2024-38827
CVE-2022-22970
CVE-2020-15250
CVE-2024-12801
CVE-2021-28170
CVE-2015-2944
CVE-2015-0886
SRCCLR-SID-2367
CVE-2017-2582
CVE-2021-24122
CVE-2024-21733
CVE-2021-33037
CVE-2020-13943
CVE-2021-30640
CVE-2021-29425
SRCCLR-SID-5295
CVE-2018-1002200
CVE-2022-38749
CVE-2022-38750
CVE-2022-38751
CVE-2022-38752
CVE-2022-41854
CVE-2024-38809
CVE-2020-5421
CVE-2023-20861
CVE-2023-20863
CVE-2022-22950
CVE-2022-22968
"

VH=0
H=0
M=0

for id in `grep 'severity_desc="Very High"' veracoderesults.txt | grep -v detailedreport | awk -F '["]' '/cve_id=/{print $2}'`
do
        if [[ $EXCEPTIONS == *"$id"* ]]
        then
                echo "Very High: $id is in exception list"
        else
                echo "Very High: $id is NOT in exception list"
                VH=$(( VH + 1 ))
        fi
done

for id in `grep 'severity_desc="High"' veracoderesults.txt | grep -v detailedreport | awk -F '["]' '/cve_id=/{print $2}'`
do
        if [[ $EXCEPTIONS == *"$id"* ]]
        then
                echo "High: $id is in exception list"
        else
                echo "High: $id is NOT in exception list"
                H=$(( H + 1 ))
        fi
done

for id in `grep 'severity_desc="Medium"' veracoderesults.txt | grep -v detailedreport | awk -F '["]' '/cve_id=/{print $2}'`
do
        if [[ $EXCEPTIONS == *"$id"* ]]
        then
                echo "Medium: $id is in exception list"
        else
                echo "Medium: $id is NOT in exception list"
                M=$(( M + 1 ))
        fi
done

echo "Very High: $VH "
echo "High: $H "
echo "Medium: $M "

if [[ $VH -gt 0 || $H -gt 0 || $M -gt 0 ]] 
then
    echo "Scan Policy: FAILED"
    exit 1
else
   echo "Scan Policy: PASSED"
fi